# -----------------------------------------------------------------------------
#   - invoked on push, pull_request, manual trigger, or schedule
#   - test under at least 3 versions of python
# -----------------------------------------------------------------------------
name: build_utils
on:
  workflow_call:
    inputs:
      dependencies:
        description: "String of comma-separated dependencies to check for upstream branches"
        required: true
        type: string
      black_version:
        description: "Black version to use"
        required: false
        default: "22.3.0"
        type: string
      skip_mypy:
        description: "Boolean to determine if mypy should be run"
        required: false
        default: false
        type: boolean
      install_type:
        description: "String of install type. Typicall dev or test"
        required: false
        default: "[dev]"
        type: string
      skip_docs:
        description: "Boolean to determine if docs should be built"
        required: false
        default: false
        type: boolean
      # secrets:
      #   notify_email:
      #     description: "Email to send notifications to"
      #     required: false
      #     default: "DEFAULT"
      #     type: string
      #   notify_password:
      #     description: "Password for email to send notifications to"
      #     required: false
      #     default: "DEFAULT"
      #     type: string

jobs:
  template_build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -le {0}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: get upstream branch name
        run: |
          if "${{ github.event_name == 'pull_request' }}" ; then
            echo "branch_name=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
          else
            echo "branch_name=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          fi
      - name: Update pip
        run: |
          python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          echo "Install requirement is ${{ inputs.install_type }}"
          pip install .${{ inputs.install_type }}
          git checkout ${branch_name}
      - name: Check for dependency branches and install if needed
        run: |
          git clone https://github.com/ihmeuw/vivarium_build_utils.git ../vivarium_build_utils
          echo "----------------------------------------"
          echo "Contents of install_dependency_branch.sh"
          echo "----------------------------------------"
          cat ../vivarium_build_utils/install_dependency_branch.sh
          echo "" 
          echo "----------------------------------------"
          for package in $(echo ${{ inputs.dependencies }} | sed "s/,/ /g"); do
            sh ../vivarium_build_utils/install_dependency_branch.sh ${package} ${branch_name} github
          done
      - name: print environment values
        run: |
          cat $GITHUB_ENV
      - name: Lint
        run: |
          pip install black==${{ inputs.black_version }} isort
          isort . --check --verbose --only-modified --diff
          echo "----------------------------------------"
          black . --check --diff
          echo "----------------------------------------"
          if "${{ inputs.skip_mypy == false }}"; then
            mypy .
          fi
      - name: Test
        run: |
          if "${{ github.event_name == 'schedule' }}"; then
            pytest --runslow ./tests
          else
            pytest ./tests
          fi
      - name: Doc build
        run: |
          if "${{ inputs.skip_docs == false }}"; then
            make html -C docs/ SPHINXOPTS="-W --keep-going -n"
          fi
      - name: Doctest
        run: |
          if "${{ inputs.skip_docs == false }}"; then
            make doctest -C docs/
          fi
      # - name: Set notify variables
      #   run: |
      #     if "${{ inputs.notify_email != 'DEFAULT' }}"; then
      #       echo "notify_email=${{ secrets.NOTIFY_EMAIL }}" >> $GITHUB_ENV
      #     else
      #       echo "notify_email=${{ inputs.notify_email }}" >> $GITHUB_ENV
      #     fi
      #     if "${{ inputs.notify_password != 'DEFAULT' }}"; then
      #       echo "notify_password=${{ secrets.NOTIFY_PASSWORD }}" >> $GITHUB_ENV
      #     else 
      #       echo "notify_password=${{ inputs.notify_password }}" >> $GITHUB_ENV
      #     fi
      #     echo "Notification email is ${{ env.notify_email }}"
      #     echo "Notification password is ${{ env.notify_password }}"
      - name: Send mail
        # Notify when cron job fails
        if: (github.event_name == 'schedule' && failure())
        uses: dawidd6/action-send-mail@v2
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.NOTIFY_EMAIL }}
          password: ${{ secrets.NOTIFY_PASSWORD }}
          # email subject
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          # email body as text
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          # comma-separated string, send email to
          to: uw_ihme_simulationscience@uw.edu
          # from email name
          from: Vivarium Notifications