# -----------------------------------------------------------------------------
#   - invoked on push, pull_request, manual trigger, or schedule
#   - test under at least 3 versions of python
# -----------------------------------------------------------------------------
name: build_utils
on:
  workflow_call:
    inputs:
      dependencies:
        description: "String of comma-separated dependencies to check for upstream branches"
        required: true
        type: string
      skip_mypy:
        description: "Boolean to determine if mypy should be run"
        required: false
        default: true
        type: boolean
      install_type:
        description: "String of install type. Typically dev or test"
        required: false
        default: "dev"
        type: string

jobs:  
  install_dependencies:
    uses: ihmeuw/vivarium_build_utils/.github/workflows/install.yml@albrja/mic-5469/modularize-workflows
    with: 
      dependencies: ${{ inputs.dependencies }}
      install_type: ${{ inputs.install_type }}
  
  next_job:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -le {0}
    steps:
      - name: Lint
        run: |
          pip install black==22.3.0 isort
          isort . --check --verbose --only-modified --diff
          echo "----------------------------------------"
          black . --check --diff
          echo "----------------------------------------"
          if "${{ inputs.skip_mypy }}" == "false"; then
            mypy .
          fi
      - name: Test
        run: |
          if "${{ github.event_name == 'schedule' }}"; then
            pytest --runslow ./tests
          else
            pytest ./tests
          fi
      - name: Doc build
        run: |
          make html -C docs/ SPHINXOPTS="-W --keep-going -n"
      - name: Doctest
        run: |
          make doctest -C docs/
      - name: Send mail
        # Notify when cron job fails
        if: (github.event_name == 'schedule' && failure())
        uses: dawidd6/action-send-mail@v2
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.NOTIFY_EMAIL }}
          password: ${{ secrets.NOTIFY_PASSWORD }}
          # email subject
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          # email body as text
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          # comma-separated string, send email to
          to: uw_ihme_simulationscience@uw.edu
          # from email name
          from: Vivarium Notifications
